baseURL = "https://tomarcher.io/"
languageCode = "en-us"
title = "Signal & Syntax by Tom Archer"
theme = "mainroad"

[pagination]
  pagerSize = 10

[params]
  aboutShowAvatar = false
  avatar = "img/avatar.png"
  mainSections = ["posts"]
  description = "Tom Archer's technical blog"

  # Full bio (we'll show the first 100 chars in a sidebar widget)
  bio = """
  Tom Archer is a longtime software developer, author, and technicalist with deep roots in Python, C++, Windows programming, and AI-driven automation. Tom started his career coding the box-office reporting & itinerary systems in Amsterdam for Holiday on Ice. Since then, he has designed and coded software for companies like IBM, AT&T, and VeriSign. Tom currently builds AI tools at Microsoft that generate technical documentation.
  """

  bioExt = """
        Tom Archer is a longtime software developer, author, and technologist with 
        deep roots in Python, C++, Windows programming, and AI-driven automation. Tom
        began his career coding the box office reporting and itinerary systems in Amsterdam for 
        Holiday on Ice. Since then, he has designed and built software for 
        companies like IBM, AT&T, and VeriSign. He currently
        develops AI tools at Microsoft that generate technical documentation.
  
        Tom helped build and run <em>CodeGuru.com</em>, once the web’s largest Windows developer 
        community. He has been recognized by Microsoft as a C++ MVP and has written a dozen technical
        books and hundreds of online articles.
  
        While very content in his current role at Microsoft, decades of experience have taught 
        Tom that there's always tomorrow to plan for. If you have a cool and 
        interesting project - especially one that blends technology, creativity, and real-world 
        impact - he's always excited to hear about it!
    """

  # Load a small custom CSS file for the "READ MORE" button and separators
  customCSS = ["css/extra.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2

# Right sidebar widgets order:
[params.sidebar]
  home   = "right"
  list   = "right"
  single = "right"
  widgets = ["bio", "disclaimer", "recent", "categories", "taglist"]

[markup]
  [markup.highlight]
    noClasses = false
    style = "dracula"
    lineNos = true