baseURL = "https://tomarcher.io/"
languageCode = "en-us"
title = "Signal & Syntax: Practical AI Coding with Tom Archer"
theme = "mainroad"

[pagination]
  pagerSize = 10

[params]
  readMore = true
  aboutShowAvatar = false
  avatar = "img/avatar.png"
  mainSections = ["posts"]
  description = "Tom Archer's technical blog"

  # Short bio (first paragraph)
  bio = """
  Tom Archer is a seasoned technical lead and engineering manager, as well as a software developer and technical author, with deep roots in Python, C++, Windows programming, and AI-driven automation. He has led teams and delivered software solutions for IBM, AT&T, Peachtree Software (Sage 500), and VeriSign. At Microsoft, Tom develops AI tools for technical documentation, drawing on decades of experience in both hands-on coding and guiding developer teams.

  Tom also helped build and run [CodeGuru.com](https://codeguru.com), once the world's largest Windows developer community. He has been recognized by Microsoft as a Visual C++ MVP and has written ten programming books and hundreds of online articles.

  While content in his current role at Microsoft, Tom believes there is always tomorrow to plan for. If you have a cool and interesting project, especially one that blends technology, creativity, and real-world impact on a fun team, he's always excited to hear about it.  

  Connect with Tom today via [LinkedIn](https://www.linkedin.com/in/tom-archer-dev/).
  """

  # Load a small custom CSS file for the "READ MORE" button and separators
  customCSS = ["css/extra.css"]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 10
  [[menu.main]]
    #name = "Bio"
    name = "behind the code"
    url  = "/bio/"
    weight = 20

[params.social]
  github   = "https://github.com/tomarcher"
  linkedin = "https://www.linkedin.com/in/tom-archer-dev/"
  rss      = true

# Right sidebar widgets order:
[params.sidebar]
  home   = "right"
  list   = "right"
  single = "right"
  widgets = ["bio", "disclaimer", "social", "recent", "categories", "taglist"]

[markup]
  [markup.highlight]
    noClasses = true
    style = "dracula"
    lineNos = true